using UnityEngine;

namespace SphereCorridor.Corridor.Grid
{
    /// <summary>
    /// Immutable floor vocabulary entry. Visual form and behavior are data, allowing
    /// future ice, damage, boost, conveyor, or healing tiles to share one grid system.
    /// </summary>
    [CreateAssetMenu(fileName = "FloorTile", menuName = "Sphere Corridor/Grid/Floor Tile")]
    public sealed class FloorTileDefinition : ScriptableObject
    {
        [SerializeField] private string stableId = "standard_floor";
        [SerializeField] private FloorTraversalKind traversalKind = FloorTraversalKind.Walkable;
        [SerializeField] private GameObject prefabOverride;
        [SerializeField] private GridPrimitiveShape fallbackShape = GridPrimitiveShape.Cube;
        [SerializeField] private Material material;
        [SerializeField, Min(0.01f)] private float thickness = 1f;
        [SerializeField] private float surfaceElevation;
        [SerializeField, Tooltip("Merge adjacent identical cells into one static object.")]
        private bool mergeAdjacentCells = true;

        public string StableId => stableId;
        public FloorTraversalKind TraversalKind => traversalKind;
        public GameObject PrefabOverride => prefabOverride;
        public GridPrimitiveShape FallbackShape => fallbackShape;
        public Material Material => material;
        public float Thickness => thickness;
        public float SurfaceElevation => surfaceElevation;
        public bool MergeAdjacentCells => mergeAdjacentCells;
        public bool IsWalkable => traversalKind != FloorTraversalKind.Gap;

        /// <summary>Configures the first geometric floor type generated by M2.1.</summary>
        public void Configure(
            string id,
            FloorTraversalKind kind,
            GameObject prefab,
            GridPrimitiveShape shape,
            Material renderMaterial,
            float tileThickness,
            float elevation,
            bool mergeRuns = true)
        {
            stableId = id;
            traversalKind = kind;
            prefabOverride = prefab;
            fallbackShape = shape;
            material = renderMaterial;
            thickness = Mathf.Max(0.01f, tileThickness);
            surfaceElevation = elevation;
            mergeAdjacentCells = mergeRuns;
        }

        /// <summary>Rejects floor types which cannot produce deterministic geometry.</summary>
        public bool IsValid(out string reason)
        {
            if (string.IsNullOrWhiteSpace(stableId))
            {
                reason = "Floor tile stable ID is empty.";
                return false;
            }

            if (thickness <= 0f)
            {
                reason = $"Floor tile '{stableId}' thickness must be positive.";
                return false;
            }

            reason = string.Empty;
            return true;
        }
    }
}
